"""
mcp_server/tools/knowledge.py
OWNER: SOORYA ← DO NOT EDIT THIS FILE

STATUS: COMPLETE ✅

TOOL 9: knowledge_search
    Required scope: read:knowledge
    DB: knowledge_base/chroma_db/ (ChromaDB collection: retail_kb)
    Input:  { query: str (required), n_results: int (optional, 1–5, default 2) }
    Output: { query, results: [{ document_id, category, title, excerpt, similarity_score }] }

Implementation notes:
    - Embeddings generated locally via all-MiniLM-L6-v2 — NO external API call.
    - Similarity score formula: 1 / (1 + l2_distance)
    - Must respond within 500ms.
    - Agent may call this multiple times per investigation with different queries.
    - ChromaDB metadata fields: category (SOP | Past Case), tags (comma-separated string)
"""
# [actual implementation is in Soorya's branch — this file is a placeholder for project structure clarity]
