"""
mcp_server/tools/knowledge.py
OWNER: SOORYA ← DO NOT EDIT THIS FILE

STATUS: COMPLETE ✅

TOOL 9: knowledge_search
    Required scope: read:knowledge
    DB: knowledge_base/chroma_db/ (ChromaDB collection: retail_kb)
    Input:  { query: str (required), n_results: int (optional, 1–5, default 2) }
    Output: { query, results: [{ document_id, category, title, excerpt, similarity_score }] }

Implementation notes:
    - Embeddings generated locally via all-MiniLM-L6-v2 — NO external API call.
    - Similarity score formula: 1 / (1 + l2_distance)
    - Must respond within 500ms.
    - Agent may call this multiple times per investigation with different queries.
    - ChromaDB metadata fields: category (SOP | Past Case), tags (comma-separated string)
"""
# [actual implementation is in Soorya's branch — this file is a placeholder for project structure clarity]
# tools/tool_9_knowledge.py
# MCP Tool: knowledge_search
# Scope required: read:knowledge
# Queries ChromaDB retail_kb collection for relevant SOPs and past cases

from knowledge_base.service import get_collection
from mcp_server.auth_middleware import check_scope, get_token_payload
from logging_config import get_logger

logger = get_logger("mcp.knowledge")

DEFAULT_N_RESULTS = 2

def knowledge_search(query: str, n_results: int = DEFAULT_N_RESULTS) -> dict:
    """
    Searches the retail knowledge base for SOPs and past cases relevant to query.

    query: natural-language search string (must be non-empty)
    n_results: number of results to return (default: 2)
    """
    err = check_scope(get_token_payload(), "read:knowledge", tool_name="knowledge_search")
    if err:
        return err

    if not query or not query.strip():
        return {
            "error": "EMPTY_QUERY",
            "message": "query must be a non-empty string",
            "tool": "knowledge_search"
        }

    try:
        collection = get_collection()

        results = collection.query(
            query_texts=[query],
            n_results=min(n_results, collection.count())
        )

        hits = []
        for i in range(len(results["ids"][0])):
            distance = results["distances"][0][i]
            hits.append({
                "doc_id": results["ids"][0][i],
                "text": results["documents"][0][i],
                "category": results["metadatas"][0][i].get("category"),
                "tags": results["metadatas"][0][i].get("tags"),
                "similarity_score": round(1 - distance, 4)
            })

        return {
            "query": query,
            "n_results": len(hits),
            "results": hits,
            "tool": "knowledge_search"
        }

    except Exception as e:
        logger.error(
            "knowledge search failed",
            extra={"event": "knowledge_error", "error_type": type(e).__name__},
            exc_info=True,
        )
        return {
            "error": "KNOWLEDGE_ERROR",
            "message": str(e),
            "tool": "knowledge_search"
        }
