"""
knowledge_base/router.py
OWNER: SOORYA ← DO NOT EDIT THIS FILE

STATUS: COMPLETE ✅
"""
# [actual implementation is in Soorya's branch]
# knowledge_api.py
# FastAPI endpoints for knowledge base management.
# Only Admin role can use these — write:knowledge scope required.
#
# POST   /api/v1/detective/knowledge              → add document
# PUT    /api/v1/detective/knowledge/{documentId} → update document  
# DELETE /api/v1/detective/knowledge/{documentId} → delete document
#
# Run: uvicorn knowledge_api:app --reload --port 8001

from fastapi import FastAPI, HTTPException, Header
from pydantic import BaseModel
from typing import Optional
import os
import jwt
import time

from knowledge_base.service import get_collection

app = FastAPI(title="ROD Knowledge API")

# ── ChromaDB setup ─────────────────────────────────────────────────────────
# Same collection your knowledge_search tool reads from (shared via
# knowledge_base/service.py) — changes here are immediately visible to
# the MCP tool, no restart needed.

JWT_SECRET  = os.getenv("JWT_SECRET", "dev-secret-change-in-prod")
_collection = get_collection()


# ── Auth helper ────────────────────────────────────────────────────────────
# Decodes the Bearer token from the Authorization header.
# Returns the payload if valid, raises 401/403 if not.

def require_scope(authorization: str, required_scope: str) -> dict:
    """
    Validates JWT from Authorization header.
    Raises HTTPException 401 if token missing/invalid.
    Raises HTTPException 403 if required scope not present.
    """
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing Bearer token")
    
    token = authorization.split(" ")[1]  # strip "Bearer " prefix
    
    try:
        payload = jwt.decode(token, JWT_SECRET, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="Token expired")
    except jwt.InvalidTokenError:
        raise HTTPException(status_code=401, detail="Invalid token")
    
    scopes = payload.get("scopes", [])
    if required_scope not in scopes:
        raise HTTPException(
            status_code=403,
            detail=f"Admin role required. Missing scope: {required_scope}"
        )
    
    return payload


# ── Request/Response models ────────────────────────────────────────────────
# Pydantic models define the shape of JSON bodies.
# FastAPI validates incoming requests against these automatically.

class AddDocumentRequest(BaseModel):
    document_text: str
    category: str           # "SOP" or "Past Case"
    tags: Optional[list[str]] = []

class UpdateDocumentRequest(BaseModel):
    document_text: str
    category: str
    tags: Optional[list[str]] = []


# ── POST /api/v1/detective/knowledge ──────────────────────────────────────
# Adds a new document to the vector store.
# Admin only (write:knowledge scope).
# Document is immediately searchable — no restart needed.

@app.post("/api/v1/detective/knowledge", status_code=201)
def add_knowledge_document(
    body: AddDocumentRequest,
    authorization: str = Header(default=None)
):
    # Check Admin scope first
    require_scope(authorization, "write:knowledge")
    
    # Validate document_text — must not be empty
    if not body.document_text or not body.document_text.strip():
        raise HTTPException(status_code=400, detail="document_text must not be empty")
    
    # Spec says max 2000 characters — chunking required for longer docs
    if len(body.document_text) > 2000:
        raise HTTPException(
            status_code=400,
            detail=f"document_text exceeds 2000 character limit ({len(body.document_text)} chars). Split into smaller chunks."
        )
    
    # Validate category
    valid_categories = {"SOP", "Past Case"}
    if body.category not in valid_categories:
        raise HTTPException(
            status_code=400,
            detail=f"category must be one of: {', '.join(valid_categories)}"
        )
    
    # Generate a document ID based on timestamp
    # In production this would be a proper sequence — fine for now
    doc_id = f"DOC-{int(time.time())}"
    tags_str = ",".join(body.tags) if body.tags else ""
    
    # upsert adds the document AND generates its embedding automatically
    # The embedding is what makes it semantically searchable
    _collection.upsert(
        ids=[doc_id],
        documents=[body.document_text],
        metadatas=[{"category": body.category, "tags": tags_str}]
    )
    
    return {
        "document_id": doc_id,
        "category": body.category,
        "tags": body.tags,
        "chunk_count": 1,
        "indexed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "message": "Document embedded and indexed. Immediately searchable."
    }


# ── PUT /api/v1/detective/knowledge/{documentId} ──────────────────────────
# Updates an existing document — re-embeds it with new text.
# Admin only. Immediate effect.

@app.put("/api/v1/detective/knowledge/{document_id}")
def update_knowledge_document(
    document_id: str,
    body: UpdateDocumentRequest,
    authorization: str = Header(default=None)
):
    require_scope(authorization, "write:knowledge")
    
    # Check document exists before updating
    # ChromaDB get() returns empty lists if ID not found
    existing = _collection.get(ids=[document_id])
    if not existing["ids"]:
        raise HTTPException(
            status_code=404,
            detail=f"Document {document_id} not found"
        )
    
    if not body.document_text or not body.document_text.strip():
        raise HTTPException(status_code=400, detail="document_text must not be empty")
    
    if len(body.document_text) > 2000:
        raise HTTPException(status_code=400, detail="document_text exceeds 2000 character limit")
    
    tags_str = ",".join(body.tags) if body.tags else ""
    
    # upsert on existing ID = update
    # ChromaDB re-generates the embedding with the new text
    # This is why updated docs are immediately searchable without restart
    _collection.upsert(
        ids=[document_id],
        documents=[body.document_text],
        metadatas=[{"category": body.category, "tags": tags_str}]
    )
    
    return {
        "document_id": document_id,
        "message": "Document re-embedded and re-indexed successfully.",
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    }


# ── DELETE /api/v1/detective/knowledge/{documentId} ───────────────────────
# Permanently removes a document from the vector store.
# Admin only. Excluded from search results immediately.

@app.delete("/api/v1/detective/knowledge/{document_id}")
def delete_knowledge_document(
    document_id: str,
    authorization: str = Header(default=None)
):
    require_scope(authorization, "write:knowledge")
    
    # Check it exists first
    existing = _collection.get(ids=[document_id])
    if not existing["ids"]:
        raise HTTPException(
            status_code=404,
            detail=f"Document {document_id} not found"
        )
    
    # Delete permanently — no soft delete, spec says immediately excluded
    _collection.delete(ids=[document_id])
    
    return {
        "document_id": document_id,
        "message": "Document permanently removed from vector store.",
        "deleted_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    }